name: MonkeyDave CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Compile with Docker
      run: |
        docker build -t monkeydave .
        docker run --rm monkeydave make
        docker cp builder:/app/MonkeyDave/play_game .

    - name: Upload Build Product
      uses: actions/upload-artifact@v4
      with:
        name: MonkeyDave-Linux-Version

        path: |
          play_game
          MonkeyDave/image_project/
          MonkeyDave/audio_project/
          MonkeyDave/font_project/
