name: MonkeyDave CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Compile with Docker
      run: |
        docker build -t monkeydave-all .
        
        docker run --name linux_builder monkeydave-all make
        docker cp linux_builder:/app/MonkeyDave/play_game .

        docker run --name win_builder monkeydave-all make -f Makefile.win
        docker cp win_builder:/app/MonkeyDave/MonkeyDave.exe .

    - name: Upload Build Product
      uses: actions/upload-artifact@v4
      with:
        name: MonkeyDave-Linux-Version

        path: |
          play_game
          MonkeyDave.exe
          MonkeyDave/image_project/
          MonkeyDave/audio_project/
          MonkeyDave/font_project/
